import useId from "../hooks/useId";

export const navbar = [
  {
    id: useId,
    title: "Institut",
    children: [
      {
        id: useId,
        label: "Ma'muriyat",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Institut nizomi",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Institut vazifalari",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Institut strukturasi",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Stomotologiya jurnali",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
    ],
    private: false,
    hidden: false,
  },
  {
    id: useId,
    title: "Fakultetlar",
    children: [
      {
        id: useId,
        label: "Stomotologiya fakulteti",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Bolalar Stomotologiyasi fakulteti",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Tibbiy pedagogik va tibbiyot fakulteti",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Xalqaro ta'lim fakulteti",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Malaka oshirish fakulteti",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Menejment fakulteti",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Xorijiy talabalar bilan ishlash fakulteti",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
    ],
    private: false,
    hidden: false,
  },
  {
    id: useId,
    title: "Faoliyat",
    children: [
      {
        id: useId,
        label: "Ilmiy faoliyat",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "O'quv-uslubiy faoliyat",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Xalqaro faoliyat",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Moliyaviy faoliyat",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Ma'naviy-ma'rifiy faoliyat",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
    ],
    private: false,
    hidden: false,
  },
  {
    id: useId,
    title: "Talabalarga",
    children: [
      {
        id: useId,
        label: "Yotoqxona qabul",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Ijara xonadonlar",
        path: "/rektorat",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Shartnoma olish",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Dars jadvali",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Xorijiy talabalar",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "O'qishni ko'chirish",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Iqtidorli talabalar",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
      {
        id: useId,
        label: "Call markazi",
        path: "/vazifa",
        private: false,
        hidden: false,
      },
    ],
    private: false,
    hidden: false,
  },
];
